# Use an official Node.js runtime as a parent image
ARG NODE_VER
FROM node:${NODE_VER}
# FROM node:20-alpine

USER node

# Set the working directory in the container
WORKDIR /app

# # Copy the package.json and package-lock.json files
# COPY app/package.json .

# # Install dependencies
# RUN yarn install

# # Copy the application code
# COPY app .

# # Expose the port Vite is running on
# EXPOSE 5173

# # Command to start the Vite app
# CMD ["yarn", "dev"]
