# Use an official Node.js runtime as a parent image
ARG NODE_VER
FROM node:${NODE_VER}
# FROM node:20-alpine

USER node

# Set the working directory in the container
WORKDIR /app

# # Copy the package.json and package-lock.json files
# COPY package.json .

# # Install dependencies
# RUN npm install

# # Copy the application code
# COPY . .

# # Expose the port Vite is running on
# EXPOSE 5173

# # Command to start the Vite app
# CMD ["npm", "run", "dev"]
