version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - myapp-network

  frontend:
    build: 
      args:
        - NODE_VER=20-alpine
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app
    networks:
      - myapp-network
    tty: true
    command: >
      sh -c "yarn install && yarn dev"

networks:
  myapp-network:
